# SSID
ssid=CAP5GHz
# Band: a = 5GHz & 6GHz (a/n/ac/ax), g = 2Ghz (b/g/n)
hw_mode=a

# Channel availability varies by country
# https://en.wikipedia.org/wiki/List_of_WLAN_channels
channel=36
# Country code
# https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
country_code=BE
# Advertises the country_code and the set of allowed channels and transmit power
ieee80211d=1
# Enables support for 5GHz DFS channels if supported (requires ieee80211d=1)
#ieee80211h=1
# Set hostapd driver (nl80211 is used with all Linux mac80211 (in-kernel) and mo
driver=nl80211
interface=wlan0

# Control interface
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
#Various settings
#beacon_int=100
#dtim_period=2
#max_num_sta=32
#rts_threshold=2347
#fragm_threshold=2346
#send_probe_response=1

# IEEE 802.11n (WiFi 4) band 2, 5 GHz configuration

ieee80211n=1
wmm_enabled=1
obss_interval=0

ht_capab=[HT40+][HT40-][SHORT-GI-20][SHORT-GI-40]


# IEEE 802.11ac (WiFi 5) configuration
ieee80211ac=1
ieee80211ax=1
# Channel width (0 = 40 MHz. 1 = 80 Mhz)
vht_oper_chwidth=1
# VHT center channel (chan + 6)
vht_oper_centr_freq_seg0_idx=42


vht_capab=[SHORT-GI-80][SU-BEAMFORMEE][MU-BEAMFORMEE]
